#ifndef CURLINC_HEADER_H
#define CURLINC_HEADER_H
/***************************************************************************
 *                                  _   _ ____  _
 *  Project                     ___| | | |  _ \| |
 *                             / __| | | | |_) | |
 *                            | (__| |_| |  _ <| |___
 *                             \___|\___/|_| \_\_____|
 *
 * Copyright (C) Daniel Stenberg, <daniel@haxx.se>, et al.
 *
 * This software is licensed as described in the file COPYING, which
 * you should have received as part of this distribution. The terms
 * are also available at https://curl.se/docs/copyright.html.
 *
 * You may opt to use, copy, modify, merge, publish, distribute and/or sell
 * copies of the Software, and permit persons to whom the Software is
 * furnished to do so, under the terms of the COPYING file.
 *
 * This software is distributed on an "AS IS" basis, WITHOUT WARRANTY OF ANY
 * KIND, either express or implied.
 *
 * SPDX-License-Identifier: curl
 *
 ***************************************************************************/

/* RETAINED REFERENCE HEADER -- not generated, and not yet generable.

   This file is the curl 8.19.0-DEV header the C tree shipped, kept verbatim. It
   is the ABI contract the Rust implementation is measured against, and it is an
   input to this build rather than an output of it.

   curl-rs-ffi/build.rs regenerates include/curl/ with cbindgen only when every
   one of the 100 exported symbols in lib/libcurl.def has a definition that
   reaches libcurl.so, and it regenerates all of them together or none of them.
   Until then it writes nothing at all: cbindgen renders only the symbols that
   exist, so a partial render would REPLACE the complete contract with a
   truncated one. Measured on this tree at 24 of 100 defined, regeneration
   dropped curl_easy_init, curl_easy_perform, curl_easy_cleanup and
   curl_easy_duphandle from easy.h among 3,289 deleted lines across eight
   headers. Every build publishes the live figures as CURL_RS_ABI_REQUIRED,
   CURL_RS_ABI_DEFINED and CURL_RS_ABI_HEADERS_GENERATED.

   A hand-written copy of cbindgen's own "Generated by curl-rs-ffi/build.rs via
   cbindgen. Do not edit by hand." marker stood here, and it was untrue in both
   halves: nothing had generated this file, and editing it by hand is exactly
   what maintaining a retained reference header means. cbindgen writes that
   marker itself, from the autogen_warning in curl-rs-ffi/cbindgen.toml, so it
   will appear here when -- and only when -- it is earned.

   What the replaced text got right is kept, because it is where those integers
   are pinned today: the Rust crate curl-rs-ffi is the source of truth for the
   option identifiers and their metadata, in curl-rs-ffi/src/ffi/opts.rs, and
   for the error codes, in curl-rs-ffi/src/ffi/codes.rs. This header is the
   contract they are pinned AGAINST, which is why it must not be overwritten
   from them while it is still the more complete of the two. */

#ifdef __cplusplus
extern "C" {
#endif

struct curl_header {
  char *name;    /* this might not use the same case */
  char *value;
  size_t amount; /* number of headers using this name  */
  size_t index;  /* ... of this instance, 0 or higher */
  unsigned int origin; /* see bits below */
  void *anchor; /* handle privately used by libcurl */
};

/* 'origin' bits */
#define CURLH_HEADER    (1 << 0) /* plain server header */
#define CURLH_TRAILER   (1 << 1) /* trailers */
#define CURLH_CONNECT   (1 << 2) /* CONNECT headers */
#define CURLH_1XX       (1 << 3) /* 1xx headers */
#define CURLH_PSEUDO    (1 << 4) /* pseudo headers */

typedef enum {
  CURLHE_OK,
  CURLHE_BADINDEX,      /* header exists but not with this index */
  CURLHE_MISSING,       /* no such header exists */
  CURLHE_NOHEADERS,     /* no headers at all exist (yet) */
  CURLHE_NOREQUEST,     /* no request with this number was used */
  CURLHE_OUT_OF_MEMORY, /* out of memory while processing */
  CURLHE_BAD_ARGUMENT,  /* a function argument was not okay */
  CURLHE_NOT_BUILT_IN   /* if API was disabled in the build */
} CURLHcode;

CURL_EXTERN CURLHcode curl_easy_header(CURL *easy,
                                       const char *name,
                                       size_t index,
                                       unsigned int origin,
                                       int request,
                                       struct curl_header **hout);

CURL_EXTERN struct curl_header *curl_easy_nextheader(CURL *easy,
                                                     unsigned int origin,
                                                     int request,
                                                     struct curl_header *prev);

#ifdef __cplusplus
} /* end of extern "C" */
#endif

#endif /* CURLINC_HEADER_H */
