#ifndef CURLINC_MPRINTF_H
#define CURLINC_MPRINTF_H
/***************************************************************************
 *                                  _   _ ____  _
 *  Project                     ___| | | |  _ \| |
 *                             / __| | | | |_) | |
 *                            | (__| |_| |  _ <| |___
 *                             \___|\___/|_| \_\_____|
 *
 * Copyright (C) Daniel Stenberg, <daniel@haxx.se>, et al.
 *
 * This software is licensed as described in the file COPYING, which
 * you should have received as part of this distribution. The terms
 * are also available at https://curl.se/docs/copyright.html.
 *
 * You may opt to use, copy, modify, merge, publish, distribute and/or sell
 * copies of the Software, and permit persons to whom the Software is
 * furnished to do so, under the terms of the COPYING file.
 *
 * This software is distributed on an "AS IS" basis, WITHOUT WARRANTY OF ANY
 * KIND, either express or implied.
 *
 * SPDX-License-Identifier: curl
 *
 ***************************************************************************/

#include <stdarg.h>
#include <stdio.h> /* needed for FILE */
#include "curl.h"  /* for CURL_EXTERN */

/* RETAINED REFERENCE HEADER -- not generated, and not yet generable.

   This file is the curl 8.19.0-DEV header the C tree shipped, kept verbatim. It
   is the ABI contract the Rust implementation is measured against, and it is an
   input to this build rather than an output of it.

   curl-rs-ffi/build.rs regenerates include/curl/ with cbindgen only when every
   one of the 100 exported symbols in lib/libcurl.def has a definition that
   reaches libcurl.so, and it regenerates all of them together or none of them.
   Until then it writes nothing at all: cbindgen renders only the symbols that
   exist, so a partial render would REPLACE the complete contract with a
   truncated one. Measured on this tree at 24 of 100 defined, regeneration
   dropped curl_easy_init, curl_easy_perform, curl_easy_cleanup and
   curl_easy_duphandle from easy.h among 3,289 deleted lines across eight
   headers. Every build publishes the live figures as CURL_RS_ABI_REQUIRED,
   CURL_RS_ABI_DEFINED and CURL_RS_ABI_HEADERS_GENERATED.

   A hand-written copy of cbindgen's own "Generated by curl-rs-ffi/build.rs via
   cbindgen. Do not edit by hand." marker stood here, and it was untrue in both
   halves: nothing had generated this file, and editing it by hand is exactly
   what maintaining a retained reference header means. cbindgen writes that
   marker itself, from the autogen_warning in curl-rs-ffi/cbindgen.toml, so it
   will appear here when -- and only when -- it is earned.

   What the replaced text got right is kept, because it is where those integers
   are pinned today: the Rust crate curl-rs-ffi is the source of truth for the
   option identifiers and their metadata, in curl-rs-ffi/src/ffi/opts.rs, and
   for the error codes, in curl-rs-ffi/src/ffi/codes.rs. This header is the
   contract they are pinned AGAINST, which is why it must not be overwritten
   from them while it is still the more complete of the two. */

#ifdef __cplusplus
extern "C" {
#endif

#ifndef CURL_TEMP_PRINTF
#if (defined(__GNUC__) || defined(__clang__) ||                         \
  defined(__IAR_SYSTEMS_ICC__)) &&                                      \
  defined(__STDC_VERSION__) && (__STDC_VERSION__ >= 199901L) &&         \
  !defined(CURL_NO_FMT_CHECKS)
#if defined(__MINGW32__) && !defined(__clang__)
#ifdef __MINGW_PRINTF_FORMAT  /* mingw-w64 3.0.0+. Needs stdio.h. */
#define CURL_TEMP_PRINTF(fmt, arg) \
  __attribute__((format(__MINGW_PRINTF_FORMAT, fmt, arg)))
#else
#define CURL_TEMP_PRINTF(fmt, arg)
#endif
#else
#define CURL_TEMP_PRINTF(fmt, arg) \
  __attribute__((format(printf, fmt, arg)))
#endif
#else
#define CURL_TEMP_PRINTF(fmt, arg)
#endif
#endif

CURL_EXTERN int curl_mprintf(const char *format, ...)
  CURL_TEMP_PRINTF(1, 2);
CURL_EXTERN int curl_mfprintf(FILE *fd, const char *format, ...)
  CURL_TEMP_PRINTF(2, 3);
CURL_EXTERN int curl_msprintf(char *buffer, const char *format, ...)
  CURL_TEMP_PRINTF(2, 3);
CURL_EXTERN int curl_msnprintf(char *buffer, size_t maxlength,
                               const char *format, ...)
  CURL_TEMP_PRINTF(3, 4);
CURL_EXTERN int curl_mvprintf(const char *format, va_list args)
  CURL_TEMP_PRINTF(1, 0);
CURL_EXTERN int curl_mvfprintf(FILE *fd, const char *format, va_list args)
  CURL_TEMP_PRINTF(2, 0);
CURL_EXTERN int curl_mvsprintf(char *buffer, const char *format, va_list args)
  CURL_TEMP_PRINTF(2, 0);
CURL_EXTERN int curl_mvsnprintf(char *buffer, size_t maxlength,
                                const char *format, va_list args)
  CURL_TEMP_PRINTF(3, 0);
CURL_EXTERN char *curl_maprintf(const char *format, ...)
  CURL_TEMP_PRINTF(1, 2);
CURL_EXTERN char *curl_mvaprintf(const char *format, va_list args)
  CURL_TEMP_PRINTF(1, 0);

#undef CURL_TEMP_PRINTF

#ifdef __cplusplus
} /* end of extern "C" */
#endif

#endif /* CURLINC_MPRINTF_H */
