// Copyright (C) Daniel Stenberg, <daniel@haxx.se>, et al.
//
// SPDX-License-Identifier: curl

//! Command-line surface of the `curl-rs` binary.
//!
//! This subtree carries the argument-parsing, help and parameter-validation
//! half of the C command-line tool. Its surface is frozen: option names,
//! aliases, argument arity, argument type and default
//! value are fixed for all 282 rows of the `aliases[]` table
//! (`src/tool_getparam.c:80`), and the `--version` banner is a machine-read
//! contract that `tests/runtests.pl:640-730` parses to decide which fixtures
//! may run. Under-reporting a capability there makes a fixture skip, while
//! over-reporting makes it run and fail.

/// The option surface and the parameter-outcome vocabulary --
/// `src/tool_getparam.c` with `src/tool_helpers.c`.
pub(crate) mod args;

/// The two generated shell-completion scripts, and where each installs --
/// `scripts/completion.pl` with `scripts/Makefile.am:34-62`.
pub(crate) mod completions;

/// The `--help` renderer, the built-in-manual scanner and the `--version`
/// printer -- `src/tool_help.c` with the generated `src/tool_listhelp.c`.
pub(crate) mod help;

/// The built-in manual -- `src/tool_hugehelp.c`, generated by
/// `src/mkhelp.pl` and reproduced by `build.rs`.
pub(crate) mod hugehelp;

/// IPFS and IPNS gateway URL rewriting -- `src/tool_ipfs.c` with
/// `src/tool_ipfs.h`.
pub(crate) mod ipfs;

/// The protocol and feature data model behind `--version` --
/// `src/tool_libinfo.c`.
pub(crate) mod libinfo;

/// The exact numeric, protocol and list acceptance rules of
/// curl 8.19.0-DEV -- `src/tool_paramhlp.c`.
pub(crate) mod paramhlp;

/// `--variable` definitions and `{{name:func}}` expansion -- `src/var.c`
/// with `src/var.h`.
pub(crate) mod vars;
