// /***************************************************************************
//  *                                  _   _ ____  _
//  *  Project                     ___| | | |  _ \| |
//  *                             / __| | | | |_) | |
//  *                            | (__| |_| |  _ <| |___
//  *                             \___|\___/|_| \_\_____|
//  *
//  * Copyright (C) Evgeny Grin (Karlson2k), <k2k@narod.ru>.
//  *
//  * This software is licensed as described in the file COPYING, which
//  * you should have received as part of this distribution. The terms
//  * are also available at https://curl.se/docs/copyright.html.
//  *
//  * You may opt to use, copy, modify, merge, publish, distribute and/or sell
//  * copies of the Software, and permit persons to whom the Software is
//  * furnished to do so, under the terms of the COPYING file.
//  *
//  * This software is distributed on an "AS IS" basis, WITHOUT WARRANTY OF ANY
//  * KIND, either express or implied.
//  *
//  * SPDX-License-Identifier: curl
//  *
//  ***************************************************************************/
//! SHA-512/256, FIPS 180-4. Supersedes `lib/curl_sha512_256.c` (805 lines) and
//! `lib/curl_sha512_256.h` (43 lines) over `sha2 0.10.9`'s `Sha512_256`.
//!
//! Every claim below carries a `path:line` citation into the C tree, because
//! the behaviour being reproduced is defined by those files and not by this
//! description.
//!
//! # The trap this module exists to defeat
//!
//! SHA-512/256 is SHA-512 run from a **different initial state** with its
//! output truncated to 32 bytes. It is neither SHA-256 nor the first 32 bytes
//! of a plain SHA-512: truncating SHA-512 gives a different answer, because the
//! state it starts from is different. Both SHA-256 and SHA-512/256 return 32
//! bytes, so choosing the wrong one compiles, satisfies every length
//! assertion, renders to the same 64 characters, and silently produces a digest
//! no server will accept.
//!
//! Three measurements in the C tree say which primitive this is:
//!
//! ```text
//!   lib/curl_sha512_256.c:405-415  the FIPS 180-4 section 5.3.6.2 initial
//!                                  state, "generated by the IV Generation
//!                                  Function as described in section 5.3.6";
//!                                  its first two words, at :408-409, are
//!                                  the pair no neighbour shares:
//!                                    H[0] = 0x22312194FC2BF72C  (:408)
//!                                    H[1] = 0x9F555FA3C84C64C2  (:409)
//!                                    ...
//!                                    H[7] = 0x0EB72DDC81C52CA2  (:415)
//!   lib/curl_sha512_256.c:83       CURL_SHA512_256_BLOCK_SIZE 128
//!   lib/curl_sha512_256.c:111      the OpenSSL arm asks the library for
//!                                  EVP_sha512_256(), never EVP_sha256(), and
//!                                  :113-115 then asserts that the context it
//!                                  gets back reports a 32-byte digest over a
//!                                  128-byte block
//! ```
//!
//! Neither neighbour matches that state. `lib/sha256.c:341` starts SHA-256 at
//! `0x6A09E667`, a 32-bit word; FIPS 180-4 starts SHA-512 at
//! `0x6A09E667F3BCC908`, the same constant widened. `0x22312194FC2BF72C` is
//! neither, and that is what makes this a distinct algorithm rather than a
//! truncation of one.
//!
//! The test module turns the distinction into an executable discriminator
//! twice over: the published `"abc"` vector of `tests/unit/unit1615.c:47-52`,
//! which the other 32-byte algorithm would instead answer as
//! `ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad`,
//! and a read of the chosen hasher's own `BlockSize`, which is 128 for this
//! algorithm and 64 for that one.
//!
//! # What was superseded, and by what
//!
//! 805 lines for one 32-byte digest, and almost all of it dispatch and
//! fallback rather than hashing. `lib/curl_sha512_256.c:30-37` records the
//! recommended order of the backend arms -- OpenSSL, GnuTLS, wolfSSL, Schannel
//! SSPI, mbedTLS, Rustls, "skip the backend if it does not support the required
//! algorithm" -- of which two are implemented there: OpenSSL through
//! `EVP_sha512_256` (`:39-67`) and GnuTLS through nettle, admitted only when
//! `SHA512_256_DIGEST_SIZE` exists (`:69-74`). `:245` then opens a complete
//! hand-written implementation for the case where no linked library offers the
//! algorithm at all.
//!
//! All of it is replaced by `sha2 0.10.9`'s `Sha512_256`, the RustCrypto
//! implementation on the `digest 0.10` generation the rest of this directory
//! already resolves to. The dispatch disappears with the alternatives: there is
//! one implementation now, so there is nothing to select between and no
//! fallback to hold in reserve.
//!
//! # The whole C contract, in four declarations
//!
//! ```text
//!   lib/curl_sha512_256.h:32  #define CURL_HAVE_SHA512_256
//!   lib/curl_sha512_256.h:34  extern const struct HMAC_params
//!                               Curl_HMAC_SHA512_256[1];
//!   lib/curl_sha512_256.h:36  #define CURL_SHA512_256_DIGEST_LENGTH 32
//!   lib/curl_sha512_256.h:38  CURLcode Curl_sha512_256it(
//!                               unsigned char *output,
//!                               const unsigned char *input,
//!                               size_t input_size);
//! ```
//!
//! Two oddities in those four lines are recorded so that nobody hunts for
//! something that is not missing. `Curl_HMAC_SHA512_256` is declared as an
//! **array of one** rather than as a scalar, which is a C declaration habit
//! with no Rust consequence: the keyed form here is `Hmac<Sha512Trunc256>` over
//! a type, and there is no table to find. And `lib/curl_sha512_256.h:43` closes
//! the include guard with the comment `/* HEADER_CURL_SHA256_H */`, naming a
//! different header -- a copy-paste artefact in the C that is deliberately not
//! propagated.
//!
//! `lib/curl_sha512_256.c:788-803` fills that parameter table with
//! `CURL_SHA512_256_BLOCK_SIZE` as the maximum key length and
//! `CURL_SHA512_256_DIGEST_SIZE` as the result length -- 128 and 32, the two
//! numbers [`BLOCK_LEN`] and [`DIGEST_LEN`] pin.
//!
//! # No `cfg`, because no feature corresponds to the C switches
//!
//! `lib/curl_sha512_256.h:28` wraps the header in `#if
//! !defined(CURL_DISABLE_DIGEST_AUTH) && !defined(CURL_DISABLE_SHA512_256)`,
//! and `:32` defines `CURL_HAVE_SHA512_256` inside it. Neither switch has a
//! counterpart among this workspace's fifteen Cargo features, and there is no
//! `tls` feature to reach for either, so a `cfg` naming one would be false --
//! and a `cfg` on a feature that does not exist compiles its item away in
//! silence. For this module that failure mode is worse than a missing function:
//! HTTP Digest would fall back to a different algorithm and authenticate
//! wrongly rather than fail to build. SHA-512/256 is therefore unconditional
//! here, and the capability macro is answered by [`available`] rather than by
//! the preprocessor.
//!
//! # One consumer, and the bytes it puts on the wire
//!
//! HTTP Digest, and nothing else. `lib/vauth/digest.c:983-1015` picks the
//! digest for a challenge by walking three ranges in order and passing a
//! **function pointer** down: `Curl_md5it` for an algorithm at or below
//! `ALGO_MD5SESS`, `Curl_sha256it` at or below `ALGO_SHA256SESS`, and
//! `Curl_sha512_256it` at `:1010` for `ALGO_SHA512_256SESS`, guarded by
//! `#ifdef CURL_HAVE_SHA512_256`; anything else falls through to
//! `CURLE_BAD_CONTENT_ENCODING` under the comment "should be unreachable".
//! That dispatch is why [`sha512_256`] takes `&[u8]` and returns a fixed-size
//! array exactly as its two siblings do -- the three have to stay
//! interchangeable, or `auth/digest.rs` has to special-case one of them.
//!
//! The algorithm names the C parses, and therefore the names `auth/digest.rs`
//! owes the wire, are `SHA-512-256` and `SHA-512-256-SESS`, alongside `MD5`,
//! `MD5-sess`, `SHA-256` and `SHA-256-SESS`. RFC 7616 is what added them.
//!
//! `:1010` pairs this digest with `auth_digest_sha256_to_ascii`, the *same*
//! renderer the 32-byte sibling uses, because both digests are 32 bytes:
//! `lib/vauth/digest.c:142-150` takes 32 bytes in, writes 65 out, and fills
//! them with `curl_msnprintf((char *)&dest[i * 2], 3, "%02x", source[i])` --
//! sixty-four **lowercase** characters plus a terminator. Rendering belongs to
//! [`crate::crypto::hex_lower`], which goes through `hex 0.4.3` and is
//! lowercase by definition; `lib/escape.c:218-227` is the uppercase neighbour
//! and is reproduced nowhere in this directory. This module returns raw bytes
//! and never a string, so it cannot get the case wrong on its own.
//!
//! Composing `HA1`, `HA2` and the response, handling `qop`, generating the
//! `cnonce` and formatting `nc` all belong to `auth/digest.rs`. This module
//! owes it two things: a digest byte-identical to the C one, and the
//! [`Sha512Trunc256`] marker so that the keyed `SHA-512-256-SESS` form names
//! the same hash.
//!
//! # 128 here, 64 in the sibling
//!
//! [`BLOCK_LEN`] is 128 (`lib/curl_sha512_256.c:83`, used as the maximum key
//! length at `:799`) where the 32-byte sibling's is 64 (`lib/sha256.c:473`),
//! while the digest lengths are identical. That is exactly what makes the two
//! easy to conflate, and `lib/hmac.c` shows what conflating them costs:
//! `:65-74` replaces a key longer than `maxkeylen` with its own digest and
//! `:87-91` pads a shorter one out to it, so the block length is what the
//! `0x36` and `0x5C` pads of `lib/hmac.c:42-43` are built over. A keyed digest
//! built on 64 here would be wrong in a way that surfaces only as a rejected
//! authentication exchange. [`crate::crypto`] pins both values and asserts the
//! doubling between them, the sibling asserts the inequality from its side, and
//! the test module below asserts it from this one.
//!
//! # The licence banner names one author, and it is not the usual one
//!
//! The twenty-three lines above reproduce `lib/curl_sha512_256.c:1-23`
//! verbatim, and `lib/curl_sha512_256.h:3-25` carries the same banner. It has
//! exactly **one** copyright line, `lib/curl_sha512_256.c:8`, naming Karlson2k
//! -- with a trailing full stop the other files in this directory do not have,
//! and with **no second copyright line of any kind**. Every other file under
//! `curl-rs-lib/src/crypto/` names the project's principal author; this one
//! does not, which makes it the most divergent banner in the directory and the
//! one thing here that must not be copied from a sibling. Doing so would assert
//! an attribution the C original does not make.
//!
//! Attribution is not boilerplate to be normalised. `reuse lint`
//! (`.github/workflows/hygiene.yml:47-50`) reads what is actually in the file,
//! and `REUSE.toml` annotates no path under `curl-rs-lib/src/`, so this header
//! is the only record there is. [`crate::crypto`] tabulates every banner in
//! this directory for the same reason, and the precedent is one directory over:
//! `util/inet.rs` alone carries an ISC/BIND banner because its C originals are
//! ISC-licensed.
//!
//! # Two in-body notes are deliberately not carried forward
//!
//! Both belong to the hand-written fallback that `lib/curl_sha512_256.c:245`
//! opens, and that fallback is not ported -- `sha2 0.10.9` supplies the
//! primitive instead -- so neither note has any code here left to describe.
//! Recorded rather than dropped in silence, because a reader comparing the two
//! files will find them and needs to know where they went:
//!
//! * `lib/curl_sha512_256.c:247-253` states that the implementation was
//!   written "for GNU libmicrohttpd" by the same author the banner names, that
//!   "the author ported the code to libcurl" under the curl licence, and that
//!   it is "a minimal version with minimal optimizations".
//! * `lib/curl_sha512_256.c:46-65` documents a defect in some NetBSD versions
//!   of SHA-512/256, citing NetBSD problem report 58039 at `:48` and again at
//!   `:161` where the workaround finalises into a doubled buffer. It is gated
//!   on `__NetBSD_Version__` ranges, the defect was in that platform's library
//!   rather than in curl, and no target of the compilation matrix is NetBSD.
//!
//! The **copyright** line in the banner is a different matter entirely and is
//! reproduced above: it covers the file, not the fallback.
//!
//! # What this module deliberately does not contain
//!
//! * **No parameter table.** `struct HMAC_params`
//!   (`lib/curl_sha512_256.c:788-803`) existed to make the digest pluggable
//!   across the backend arms, carrying three function pointers, a context size,
//!   a block length and a result length. `hmac 0.12.1` recovers both lengths
//!   from the type itself and there is one implementation to point at, so the
//!   table has no job left.
//! * **No `void`-returning wrappers.** `lib/curl_sha512_256.c:771-784` wraps
//!   update and finish to discard their `CURLcode` and to narrow a length to
//!   `unsigned int`, purely so that the function pointers in that table match.
//!   Nothing is narrowed here and nothing is discarded.
//! * **No local error type and no `Result`.** See [`sha512_256`] for why the C
//!   signature is fallible and this one is not. Were a fallible signature ever
//!   needed, the answer is `crate::error::CURLcode`, never a type declared in
//!   this file.
//! * **No `--version` feature token.** [`available`] answers the
//!   `CURL_HAVE_SHA512_256` question for the `sha512-256:` row of
//!   `src/curlinfo.c` and for nothing else. The banner vocabulary is fixed and
//!   curl publishes no such token in it; `crate::version` owns that decision,
//!   and this module does not reach for it from here.
//!
//! # The version pin is load-bearing
//!
//! `sha2` is pinned at `=0.10.9` once, in the workspace manifest's
//! `[workspace.dependencies]`, and inherited by `curl-rs-lib/Cargo.toml` with
//! `{ workspace = true }`. Do not restate the version here and do not advance
//! it. `sha2 0.11.0` declares a minimum supported Rust version of 1.85 against
//! this project's floor of 1.75, and it moves to `digest 0.11`, which would put
//! two `digest` generations in one graph and stop `Hmac<Sha512Trunc256>` from
//! compiling at all -- a build break, not a preference. `deny.toml` bans
//! `digest:>=0.11.0` outright so that even a whole-graph migration, which would
//! leave no duplicate for its `multiple-versions` policy to catch, still fails.
//!
//! No `sha2` feature is enabled from here. `asm` in particular is left off:
//! performance is not a goal of this work, and where a choice exists between a
//! faster design and a more faithful one, the faithful one wins. Nothing here
//! may union a second cryptographic provider into the graph either -- Cargo
//! unions features across the whole graph, `ring` is pinned explicitly at the
//! root, `aws-lc-rs` is banned there by name, and `prefer-post-quantum` is left
//! out because a hybrid key exchange changes the bytes of the ClientHello.
//!
//! # Gates
//!
//! Each pattern carries a character class on its first letter so that it cannot
//! match the line it is written on, which keeps every gate runnable against
//! this file itself. The convention is recorded in [`crate::crypto`].
//!
//! ```sh
//! # The attribution assertions, and the second is the one that matters most
//! # for this file. Prints 1, then 0, then a single line.
//! grep -c '[E]vgeny Grin'     curl-rs-lib/src/crypto/sha512_256.rs
//! grep -c '[D]aniel Stenberg' curl-rs-lib/src/crypto/sha512_256.rs
//! grep -n '[C]opyright'       curl-rs-lib/src/crypto/sha512_256.rs
//!
//! # Exactly one licence identifier line. Prints 1.
//! grep -c 'SPDX-License-Ident[i]fier: curl' \
//!   curl-rs-lib/src/crypto/sha512_256.rs
//!
//! # The two in-body notes are referenced, never reproduced: every hit is
//! # inside the module documentation above, beside a path:line citation.
//! grep -n '[l]ibmicrohttpd\|[g]nats.netbsd.org' \
//!   curl-rs-lib/src/crypto/sha512_256.rs
//!
//! # This file adds no exemption to the crate-root safety attribute and names
//! # no keyword that would need one. Must print nothing.
//! grep -n '[u]nsafe' curl-rs-lib/src/crypto/sha512_256.rs
//!
//! # The wrong primitive must not appear at all. The only mention of the
//! # sibling anywhere in this file is the lowercase module path
//! # `crypto::sha256` in the test module's cross-check, so the type-name
//! # pattern finds nothing. Must print nothing.
//! grep -n '[S]ha256' curl-rs-lib/src/crypto/sha512_256.rs
//!
//! # There is no `tls` feature, and the capability macro is not a cfg. Both
//! # must print nothing outside the documentation above.
//! grep -nE 'feature *= *"[t]ls"' curl-rs-lib/src/crypto/sha512_256.rs
//! grep -n 'cfg.*[C]URL_HAVE_SHA512_256' \
//!   curl-rs-lib/src/crypto/sha512_256.rs
//!
//! # The pin, and the single digest generation it exists to preserve.
//! cargo tree -p curl-rs-lib -i sha2    # sha2 v0.10.9
//! cargo tree -p curl-rs-lib -i digest  # digest v0.10.x, once
//! ```

use ::sha2::{Digest, Sha512_256};

/// Length of a SHA-512/256 digest in bytes.
///
/// `lib/curl_sha512_256.h:36` defines `CURL_SHA512_256_DIGEST_LENGTH 32`,
/// `lib/curl_sha512_256.c:89` ties `CURL_SHA512_256_DIGEST_SIZE` to it, and
/// `:801` repeats the 32 as the result length of the keyed parameter table.
/// `lib/curl_sha512_256.c:401` asserts that the header and the implementation
/// agree on the number, which is the C tree's own admission that two
/// definitions of one length can drift.
///
/// It is contractual rather than chosen. `lib/vauth/digest.c:143-145` sizes its
/// ASCII destination at 65 from this length, and that renderer is shared with
/// the other 32-byte digest, so the two algorithms are interchangeable at the
/// call site precisely because this number is the same for both.
pub(crate) const DIGEST_LEN: usize = 32;

/// SHA-512/256's compression block size in bytes -- **128, not 64**.
///
/// `lib/curl_sha512_256.c:83` defines `CURL_SHA512_256_BLOCK_SIZE 128` and
/// `:799` uses it as the maximum key length of `Curl_HMAC_SHA512_256`, which is
/// where the C tree recorded a block size. The two are the same number for a
/// reason: `lib/hmac.c:65-74` replaces a key longer than the block with its own
/// digest and `:87-91` pads a shorter one out to the block, so the block length
/// is the largest key length that carries any information.
///
/// Nothing in this crate computes with this constant. `hmac 0.12.1` reads the
/// same number off the hasher's `BlockSize` for itself, so the value exists
/// here to be documented and asserted -- and the assertion is the point,
/// because the sibling 32-byte digest of `crate::crypto::sha256` has a
/// `BLOCK_LEN` of **64** while its `DIGEST_LEN` is the same 32. The two must
/// never be conflated: [`crate::crypto`] pins both and asserts the doubling,
/// and the test module below asserts the inequality against the sibling
/// directly rather than trusting this comment.
#[allow(dead_code)]
pub(crate) const BLOCK_LEN: usize = 128;

/// The `digest` marker type for SHA-512/256, published so that
/// [`crate::crypto::hmac`] can instantiate `Hmac<Sha512Trunc256>` without
/// naming the `sha2` crate a second time.
///
/// The spelling is the one item here that is not curl's. `sha2` names the type
/// after the FIPS designation, and a name of that shape declared in this crate
/// would trip `clippy::non_camel_case_types`, which the zero-warnings gate
/// admits no instance of. The alias therefore carries the older RustCrypto
/// spelling, which is upper camel case throughout, and the lint is left alone:
/// no allowance is written for it here, and certainly none at module scope.
///
/// The name is contractual, not a local preference. `crypto/hmac.rs:52` imports
/// it as `use super::sha512_256::Sha512Trunc256;` and `:176` keys through it,
/// and both keyed siblings publish the same shape, so `crypto/hmac.rs` imports
/// one marker per algorithm rather than one crate per algorithm.
///
/// It also stands in for the coherence the whole directory depends on.
/// `Hmac<D>` bounds `D` on the `digest 0.10` core traits, so an
/// `Hmac<Sha512Trunc256>` that compiles at all is the compiler's own proof that
/// `sha2` and `hmac` resolved to one `digest` generation. The test module
/// asserts that, and asserts in addition that the block size behind the alias
/// is 128 -- which no configuration of the other 32-byte algorithm could
/// satisfy.
#[allow(dead_code)]
pub(crate) type Sha512Trunc256 = Sha512_256;

/// Whether this build provides the digest: the authority for
/// `CURL_HAVE_SHA512_256`.
///
/// `lib/curl_sha512_256.h:28-32` defines that macro under `#if
/// !defined(CURL_DISABLE_DIGEST_AUTH) && !defined(CURL_DISABLE_SHA512_256)`,
/// and `src/curlinfo.c` prints the `sha512-256: ` row from it. Neither switch
/// has a counterpart among this workspace's fifteen Cargo features, so no build
/// configuration can remove the digest -- and there is nothing else to
/// condition the answer on, because this module carries no `#[cfg]` on any
/// item, `sha2` is a non-optional dependency, and [`sha512_256`] is a pure
/// function with no initialisation step that can be refused.
///
/// It is a function rather than a `const` so that the single public accessor,
/// [`crate::version::has_sha512_256`], delegates to the module that owns the
/// implementation instead of restating the conclusion. `crate::version` pins
/// this signature with a `const _: fn() -> bool` beside its engine registry, so
/// the claim that the primitive exists cannot outlive the primitive. If the
/// digest ever becomes conditional, this is the one expression that changes and
/// every diagnostic that reads it follows automatically.
///
/// Answering `true` here does **not** turn the diagnostic row on. C's macro has
/// two conditions and `crate::version::has_sha512_256` carries both, so the row
/// still reports what the HTTP Digest half of the condition can support.
///
/// Deliberately **not** exposed as a `--version` feature token: C publishes no
/// such token, and `curl_version_info()->feature_names` must keep exactly the
/// names it has always held.
pub(crate) fn available() -> bool {
    true
}

/// Digest a whole message: `Curl_sha512_256it`
/// (`lib/curl_sha512_256.c:750-768`).
///
/// Returns the 32 raw bytes. Rendering to ASCII is
/// [`crate::crypto::hex_lower`]'s job, and it is lowercase because every digest
/// curl puts on the wire is written with `"%02x"`
/// (`lib/vauth/digest.c:142-150`).
///
/// # Why this cannot fail
///
/// The C function returns a `CURLcode` (`lib/curl_sha512_256.h:38-39`) and
/// `lib/curl_sha512_256.c:756-767` shows where the value comes from: the
/// initialisation step first, then update, then finish. In the OpenSSL arm the
/// first of those genuinely can fail --
/// `lib/curl_sha512_256.c:103-123` creates an `EVP_MD_CTX`, returns
/// `CURLE_OUT_OF_MEMORY` at `:109` when the allocation is refused and
/// `CURLE_FAILED_INIT` at `:122` when the digest cannot be selected -- which is
/// the whole reason the entry point is fallible. The bundled arm's own wrappers
/// at `:771-784` then discard the code with the comment "hypothetically the
/// function may fail, but assume it does not".
///
/// There is one implementation here. It allocates nothing, asks the operating
/// system for nothing, and has no initialisation step that can be refused, so
/// there is no failure to report. An infallible signature is the honest one; a
/// `Result` that is always successful would oblige every call site to handle a
/// case that cannot arise, and would invite the reflex of discarding it.
///
/// # The shape is shared with the other two Digest hashes
///
/// `lib/vauth/digest.c:983-1015` chooses between `Curl_md5it`, `Curl_sha256it`
/// and `Curl_sha512_256it` through a function pointer, so the three must stay
/// interchangeable. All three Rust counterparts therefore take `&[u8]` and
/// return a fixed-size array, which lets `auth/digest.rs` dispatch over them
/// without special-casing one.
///
/// The C wrote its answer through an output pointer; this returns the array. An
/// out-parameter was necessary there only because a `CURLcode` occupied the
/// return slot, and with nothing to report the digest comes back by value --
/// which also removes the caller's obligation to have sized a buffer correctly.
#[allow(dead_code)]
pub(crate) fn sha512_256(input: &[u8]) -> [u8; DIGEST_LEN] {
    let mut hasher = Sha512_256::new();
    hasher.update(input);
    hasher.finalize().into()
}

/// The incremental form: construct, feed any number of times, finish once.
///
/// This is the C's three-step sequence, which the parameter table at
/// `lib/curl_sha512_256.c:788-803` exposed as `Curl_sha512_256_init`
/// (`:103`), `Curl_sha512_256_update_i` (`:771`) and
/// `Curl_sha512_256_finish_v` (`:780`). Only HMAC ever drove those three
/// directly, and `hmac 0.12.1` drives the hasher itself now, so this type
/// exists for a different reason: `crate::crypto` records that a caller feeding
/// a digest in pieces should write the same code whichever algorithm it holds,
/// and the method sequence here matches both incremental siblings for that
/// reason.
///
/// Streaming changes nothing observable: the bytes a streamed digest produces
/// are the bytes the one-shot form produces, which the test module asserts
/// across every chunk boundary that could plausibly differ -- including the
/// 128-byte block boundary that distinguishes this algorithm.
///
/// The type name mirrors [`Sha512Trunc256`] and for the same reason, and
/// `crate::crypto` deliberately does not re-export it: the name is this
/// module's choice rather than something the target layout fixes, so callers
/// reach it through the module path.
#[derive(Clone, Default)]
#[allow(dead_code)]
pub(crate) struct Sha512Trunc256Context {
    hasher: Sha512_256,
}

impl Sha512Trunc256Context {
    /// A fresh context: `Curl_sha512_256_init`
    /// (`lib/curl_sha512_256.c:103`, and `:396` in the bundled arm, where the
    /// FIPS 180-4 initial state of `:405-415` is written out by hand).
    ///
    /// [`Default`] is derived alongside this and produces the same value, so a
    /// caller in a generic position is not forced through the inherent
    /// constructor.
    #[allow(dead_code)]
    pub(crate) fn new() -> Self {
        Self {
            hasher: Sha512_256::new(),
        }
    }

    /// Feed the next chunk: `Curl_sha512_256_update`, wrapped for the parameter
    /// table at `lib/curl_sha512_256.c:771-777`.
    ///
    /// Any number of calls in any chunking; the digest depends only on the
    /// concatenation of everything fed. The C wrapper took an `unsigned int`
    /// length so that its signature matched the function pointer, narrowing a
    /// `size_t` on the way in. Nothing narrows here -- the slice carries its
    /// own `usize` length the whole way down -- so a message longer than
    /// `u32::MAX` cannot be silently truncated.
    #[allow(dead_code)]
    pub(crate) fn update(&mut self, input: &[u8]) {
        self.hasher.update(input);
    }

    /// Finish and return the digest: `Curl_sha512_256_finish`, wrapped at
    /// `lib/curl_sha512_256.c:780-784`.
    ///
    /// Consuming `self` is stricter than the C sequence, where nothing stopped
    /// a caller from finalising the same context twice. Here a second call does
    /// not compile.
    #[allow(dead_code)]
    pub(crate) fn finalize(self) -> [u8; DIGEST_LEN] {
        self.hasher.finalize().into()
    }

    /// [`Sha512Trunc256Context::finalize`] under the name the incremental MD5
    /// context publishes.
    ///
    /// Both spellings exist deliberately, and both siblings carry the same
    /// pair. `finalize` is what the `digest` traits call the operation;
    /// `finish` is what `Md5Context` publishes, and the promise that a caller
    /// has one shape for every algorithm holds only if the terminal method
    /// answers to the same name in all three. Rather than break one of the two
    /// contracts, both names resolve to the same work.
    #[allow(dead_code)]
    pub(crate) fn finish(self) -> [u8; DIGEST_LEN] {
        self.finalize()
    }
}

// Tests -- where the coverage of tests/unit/unit1615.c now lives
//
// `tests/unit/unit1615.c` (152 lines) is the C unit test for this digest, and
// `tests/data/test1615` is named "SHA-512/256 unit tests" and gates on
// `<features>unittest</features>` together with the `sha512-256` label. This
// binary does not advertise `unittest`, so that fixture skips -- and it could
// not run in any case, because it links a debug static library and calls the
// internal `Curl_sha512_256it` symbol, which a Rust static library genuinely
// does not place in its symbol table. Relocating the assertions here is the
// recorded response to that; re-exporting internals to make the C program link
// instead is not, because it would destroy the encapsulation this crate
// depends on.
//
// All EIGHT of that file's vectors are reproduced, in its order, under the
// names it gives them. The byte tables carry `#[rustfmt::skip]` and keep the
// C's eleven-eleven-ten row grouping so that a reviewer can diff them against
// `tests/unit/unit1615.c:36-109` line for line. Vector 3 is the published
// FIPS 180-4 example and is the one assertion that proves the right primitive
// was chosen.
//
// Two of the eight inputs are constructed rather than quoted, and both are
// length-checked before they are hashed, so that a construction mistake
// surfaces as a length failure naming the vector rather than as an unexplained
// digest mismatch.

#[cfg(test)]
mod tests {
    use super::{
        available, sha512_256, Sha512Trunc256, Sha512Trunc256Context,
        BLOCK_LEN, DIGEST_LEN,
    };
    use crate::crypto::{hex_lower, SHA256_HEX_BUF_LEN};
    use ::hmac::{Hmac, Mac};
    use ::sha2::digest::core_api::BlockSizeUser;
    use ::sha2::digest::typenum::Unsigned;

    /// `tests/unit/unit1615.c:35`.
    const TEST_STR1: &[u8] = b"1";

    /// `tests/unit/unit1615.c:36-40`.
    #[rustfmt::skip]
    const PRECOMP_HASH1: [u8; DIGEST_LEN] = [
        0x18, 0xd2, 0x75, 0x66, 0xbd, 0x1a, 0xc6, 0x6b, 0x23, 0x32, 0xd8,
        0xc5, 0x4a, 0xd4, 0x3f, 0x7b, 0xb2, 0x20, 0x79, 0xc9, 0x06, 0xd0,
        0x5f, 0x49, 0x1f, 0x3f, 0x07, 0xa2, 0x8d, 0x5c, 0x69, 0x90,
    ];

    /// `tests/unit/unit1615.c:41`.
    const TEST_STR2: &[u8] = b"hello-you-fool";

    /// `tests/unit/unit1615.c:42-46`.
    #[rustfmt::skip]
    const PRECOMP_HASH2: [u8; DIGEST_LEN] = [
        0xaf, 0x6f, 0xb4, 0xb0, 0x13, 0x9b, 0xee, 0x13, 0xd1, 0x95, 0x3c,
        0xb8, 0xc7, 0xcd, 0x5b, 0x19, 0xf9, 0xcd, 0xcd, 0x21, 0xef, 0xdf,
        0xa7, 0x42, 0x5c, 0x07, 0x13, 0xea, 0xcc, 0x1a, 0x39, 0x76,
    ];

    /// `tests/unit/unit1615.c:47`.
    const TEST_STR3: &[u8] = b"abc";

    /// `tests/unit/unit1615.c:48-52` -- THE TRAP DETECTOR.
    ///
    /// This is the published FIPS 180-4 SHA-512/256 example for the message
    /// `"abc"`, and it is the single assertion in this file that proves the
    /// implementation selected the right primitive. Had it reached for the
    /// other 32-byte algorithm instead, the answer here would be
    /// `ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad`
    /// -- the same length, correctly rendered, and completely wrong.
    /// The C spells these particular bytes in uppercase where
    /// its other seven vectors are lowercase, which is itself a marker that
    /// this row was copied from the standard rather than produced by running
    /// the code.
    #[rustfmt::skip]
    const PRECOMP_HASH3: [u8; DIGEST_LEN] = [
        0x53, 0x04, 0x8E, 0x26, 0x81, 0x94, 0x1E, 0xF9, 0x9B, 0x2E, 0x29,
        0xB7, 0x6B, 0x4C, 0x7D, 0xAB, 0xE4, 0xC2, 0xD0, 0xC6, 0x34, 0xFC,
        0x6D, 0x46, 0xE0, 0xE2, 0xF1, 0x31, 0x07, 0xE7, 0xAF, 0x23,
    ];

    /// `tests/unit/unit1615.c:53` -- empty, zero size input.
    const TEST_STR4: &[u8] = b"";

    /// `tests/unit/unit1615.c:54-58`.
    #[rustfmt::skip]
    const PRECOMP_HASH4: [u8; DIGEST_LEN] = [
        0xc6, 0x72, 0xb8, 0xd1, 0xef, 0x56, 0xed, 0x28, 0xab, 0x87, 0xc3,
        0x62, 0x2c, 0x51, 0x14, 0x06, 0x9b, 0xdd, 0x3a, 0xd7, 0xb8, 0xf9,
        0x73, 0x74, 0x98, 0xd0, 0xc0, 0x1e, 0xce, 0xf0, 0x96, 0x7a,
    ];

    /// `tests/unit/unit1615.c:59-61` -- one 52-character run of mixed case,
    /// written twice, so 104 bytes: long enough to fill the first 128-byte
    /// block without spilling into a second.
    ///
    /// The line continuation swallows the newline and the leading whitespace
    /// that follows it, so the literal is exactly the two runs concatenated.
    /// [`the_constructed_inputs_have_the_lengths_the_c_literals_have`] asserts
    /// the 104 rather than leaving it to inspection.
    const TEST_STR5: &[u8] =
        b"abcdefghijklmnopqrstuvwxyzzyxwvutsrqponMLKJIHGFEDCBA\
          abcdefghijklmnopqrstuvwxyzzyxwvutsrqponMLKJIHGFEDCBA";

    /// `tests/unit/unit1615.c:62-66`.
    #[rustfmt::skip]
    const PRECOMP_HASH5: [u8; DIGEST_LEN] = [
        0xad, 0xe9, 0x5d, 0x55, 0x3b, 0x9e, 0x45, 0x69, 0xdb, 0x53, 0xa4,
        0x04, 0x92, 0xe7, 0x87, 0x94, 0xff, 0xc9, 0x98, 0x5f, 0x93, 0x03,
        0x86, 0x45, 0xe1, 0x97, 0x17, 0x72, 0x7c, 0xbc, 0x31, 0x15,
    ];

    /// `tests/unit/unit1615.c:67-74` -- the long path, 378 bytes, spanning
    /// three 128-byte blocks with the final one partly filled.
    ///
    /// Copied literally from the C rather than rebuilt by repetition: the
    /// segment count is what an off-by-one would change, and the digest would
    /// then differ for a reason having nothing to do with the hash. Six runs of
    /// eleven `/long` segments -- 55 characters each -- and a seventh line
    /// carrying four more plus the query string.
    const TEST_STR6: &[u8] =
        b"/long/long/long/long/long/long/long/long/long/long/long\
          /long/long/long/long/long/long/long/long/long/long/long\
          /long/long/long/long/long/long/long/long/long/long/long\
          /long/long/long/long/long/long/long/long/long/long/long\
          /long/long/long/long/long/long/long/long/long/long/long\
          /long/long/long/long/long/long/long/long/long/long/long\
          /long/long/long/long/path?with%20some=parameters";

    /// `tests/unit/unit1615.c:75-79`.
    #[rustfmt::skip]
    const PRECOMP_HASH6: [u8; DIGEST_LEN] = [
        0xbc, 0xab, 0xc6, 0x2c, 0x0a, 0x22, 0xd5, 0xcb, 0xac, 0xac, 0xe9,
        0x25, 0xcf, 0xce, 0xaa, 0xaf, 0x0e, 0xa1, 0xed, 0x42, 0x46, 0x8a,
        0xe2, 0x01, 0xee, 0x2f, 0xdb, 0x39, 0x75, 0x47, 0x73, 0xf1,
    ];

    /// `tests/unit/unit1615.c:80`.
    const TEST_STR7: &[u8] = b"Simple string.";

    /// `tests/unit/unit1615.c:81-85`.
    #[rustfmt::skip]
    const PRECOMP_HASH7: [u8; DIGEST_LEN] = [
        0xde, 0xcb, 0x3c, 0x81, 0x65, 0x4b, 0xa0, 0xf5, 0xf0, 0x45, 0x6b,
        0x7e, 0x61, 0xf5, 0x0d, 0xf5, 0x38, 0xa4, 0xfc, 0xb1, 0x8a, 0x95,
        0xff, 0x59, 0xbc, 0x04, 0x82, 0xcf, 0x23, 0xb2, 0x32, 0x56,
    ];

    /// `tests/unit/unit1615.c:86-104` -- the `255..1` sequence, 255 bytes.
    ///
    /// The C writes all 255 values out as literals and labels them
    /// "255..1 sequence"; generating the same sequence keeps the vector honest
    /// without transcribing a table whose only content is its own order. Note
    /// that it stops at 1 and never reaches 0, and that
    /// `CURL_ARRAYSIZE(test_seq8)` at `tests/unit/unit1615.c:146` passes the
    /// whole array rather than subtracting a terminator as the seven string
    /// vectors do.
    fn test_seq8() -> Vec<u8> {
        (1u8..=255).rev().collect()
    }

    /// `tests/unit/unit1615.c:105-109`.
    #[rustfmt::skip]
    const PRECOMP_HASH8: [u8; DIGEST_LEN] = [
        0x22, 0x31, 0xf2, 0xa1, 0xb4, 0x89, 0xb2, 0x44, 0xf7, 0x66, 0xa0,
        0xb8, 0x31, 0xed, 0xb7, 0x73, 0x8a, 0x34, 0xdc, 0x11, 0xc8, 0x2c,
        0xf2, 0xb5, 0x88, 0x60, 0x39, 0x6b, 0x5c, 0x06, 0x70, 0x37,
    ];

    /// The two constructed inputs really are the lengths the C literals have.
    ///
    /// Asserted before anything is hashed, and separately from the digests, so
    /// that a mistake in a line continuation or in the sequence bounds reports
    /// itself as a length rather than as an unexplained mismatch.
    #[test]
    fn the_constructed_inputs_have_the_lengths_the_c_literals_have() {
        // 52 characters written twice: tests/unit/unit1615.c:59-61.
        assert_eq!(TEST_STR5.len(), 104);
        assert_eq!(&TEST_STR5[..52], &TEST_STR5[52..]);

        // Six 55-character runs plus a 48-character tail:
        // tests/unit/unit1615.c:67-74.
        assert_eq!(TEST_STR6.len(), 6 * 55 + 48);
        assert_eq!(TEST_STR6.len(), 378);
        assert!(TEST_STR6.starts_with(b"/long/long"));
        assert!(TEST_STR6.ends_with(b"/path?with%20some=parameters"));

        // 255 values, descending, never reaching zero:
        // tests/unit/unit1615.c:86-104.
        let seq = test_seq8();
        assert_eq!(seq.len(), 255);
        assert_eq!(seq.first(), Some(&255u8));
        assert_eq!(seq.last(), Some(&1u8));
        assert!(!seq.contains(&0u8));
        assert!(seq.windows(2).all(|pair| pair[0] == pair[1] + 1));
    }

    /// All eight vectors of `tests/unit/unit1615.c`, in its order.
    ///
    /// Compared as raw arrays rather than through the hex helper, because that
    /// is the form `verify_memory` compares at `tests/unit/unit1615.c:119`
    /// through `:147`, and this test is the relocation of those eight
    /// assertions.
    #[test]
    fn one_shot_reproduces_every_unit1615_vector() {
        assert_eq!(sha512_256(TEST_STR1), PRECOMP_HASH1);
        assert_eq!(sha512_256(TEST_STR2), PRECOMP_HASH2);
        assert_eq!(sha512_256(TEST_STR3), PRECOMP_HASH3);
        assert_eq!(sha512_256(TEST_STR4), PRECOMP_HASH4);
        assert_eq!(sha512_256(TEST_STR5), PRECOMP_HASH5);
        assert_eq!(sha512_256(TEST_STR6), PRECOMP_HASH6);
        assert_eq!(sha512_256(TEST_STR7), PRECOMP_HASH7);
        assert_eq!(sha512_256(&test_seq8()), PRECOMP_HASH8);
    }

    /// The published FIPS 180-4 example, asserted a second time in the form it
    /// would travel in.
    ///
    /// Written out as the lowercase hex an `Authorization` header would carry,
    /// with the answer the other 32-byte algorithm gives for the same input
    /// asserted to be different. Nothing about this is redundant: the array
    /// comparison above proves the digest, and this proves that the digest
    /// renders as the standard publishes it and that it is not the neighbour's.
    #[test]
    fn the_published_abc_vector_is_the_one_the_standard_publishes() {
        let rendered = hex_lower(&sha512_256(TEST_STR3));
        assert_eq!(
            rendered,
            "53048e2681941ef99b2e29b76b4c7dabe4c2d0c634fc6d46e0e2f13107e7af23"
        );

        // The wrong-primitive answer, spelled out so that a failure of the
        // assertion above can be recognised on sight.
        assert_ne!(
            rendered,
            "ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad"
        );
    }

    /// The concrete guard against the confusion this module documents.
    ///
    /// Both algorithms answer `"abc"` with 32 bytes, so length proves nothing
    /// and only the values separate them. Asserted at the digest, at the block
    /// length, and at the rendered form, because each is a place where the
    /// wrong choice would go unnoticed.
    #[test]
    fn the_digest_is_not_the_other_thirty_two_byte_digests() {
        let ours = sha512_256(TEST_STR3);
        let sibling = crate::crypto::sha256::sha256(TEST_STR3);

        assert_eq!(ours.len(), sibling.len());
        assert_ne!(ours, sibling);
        assert_ne!(hex_lower(&ours), hex_lower(&sibling));

        // And across every one of the eight inputs, not only the published
        // one, so the inequality cannot hold by coincidence on a single value.
        let inputs: [&[u8]; 7] = [
            TEST_STR1, TEST_STR2, TEST_STR3, TEST_STR4, TEST_STR5, TEST_STR6,
            TEST_STR7,
        ];
        for input in inputs {
            assert_ne!(
                sha512_256(input),
                crate::crypto::sha256::sha256(input),
                "the two 32-byte digests agreed on a {}-byte input",
                input.len()
            );
        }
        assert_ne!(
            sha512_256(&test_seq8()),
            crate::crypto::sha256::sha256(&test_seq8())
        );
    }

    /// The lengths the C parameter table fixes, and the one that must not be
    /// the sibling's.
    ///
    /// `lib/curl_sha512_256.c:83` gives the block as 128 and `:799` uses it as
    /// the maximum key length; `lib/sha256.c:473` gives the sibling's as 64.
    /// The digest lengths are identical, which is what makes the two easy to
    /// conflate, so the difference is asserted rather than assumed -- and
    /// asserted here as well as in `crate::crypto` so that a failure names the
    /// algorithms rather than only a line number.
    #[test]
    fn the_block_length_is_twice_the_siblings_while_the_digest_matches_it() {
        assert_eq!(DIGEST_LEN, 32);
        assert_eq!(BLOCK_LEN, 128);

        let sibling_block = crate::crypto::sha256::BLOCK_LEN;
        assert_eq!(sibling_block, 64);
        assert_ne!(BLOCK_LEN, sibling_block);
        assert_eq!(BLOCK_LEN, sibling_block * 2);
        assert_eq!(DIGEST_LEN, crate::crypto::sha256::DIGEST_LEN);

        assert_eq!(sha512_256(b"anything").len(), DIGEST_LEN);
        assert_eq!(Sha512Trunc256Context::new().finalize().len(), DIGEST_LEN);
        assert_eq!(Sha512Trunc256Context::default().finish().len(), DIGEST_LEN);
    }

    /// The hasher itself reports a 128-byte block, which no configuration of
    /// the sibling could.
    ///
    /// Read off the type rather than taken from [`BLOCK_LEN`], so this is a
    /// second, independent witness that the primitive behind the alias is the
    /// SHA-512 family member and not the SHA-256 one. `lib/hmac.c:87-91` pads
    /// the key out to exactly this length, and `hmac 0.12.1` reads the same
    /// number from the same place, so the value asserted here is the one a
    /// keyed digest will actually use.
    #[test]
    fn the_hashers_own_block_size_is_the_one_the_c_table_records() {
        let from_the_type = <Sha512Trunc256 as BlockSizeUser>::BlockSize::USIZE;
        assert_eq!(from_the_type, 128);
        assert_eq!(from_the_type, BLOCK_LEN);
        assert_eq!(
            from_the_type,
            <Sha512Trunc256 as BlockSizeUser>::block_size()
        );
        assert_ne!(from_the_type, crate::crypto::sha256::BLOCK_LEN);
    }

    /// A streamed digest must equal the one-shot digest of the same bytes.
    ///
    /// The splits are the ones that can plausibly differ: nothing fed, one
    /// byte, one byte short of the 128-byte block, exactly the block, one byte
    /// past it, and everything at once. The block boundary is the interesting
    /// one here and it is 128 rather than 64, which is why [`BLOCK_LEN`] is
    /// used to derive the splits instead of a literal.
    #[test]
    fn incremental_agrees_with_one_shot_across_chunk_boundaries() {
        let message = test_seq8();
        assert!(message.len() > BLOCK_LEN);

        for split in [
            0usize,
            1,
            BLOCK_LEN - 1,
            BLOCK_LEN,
            BLOCK_LEN + 1,
            message.len(),
        ] {
            let mut ctx = Sha512Trunc256Context::new();
            ctx.update(&message[..split]);
            ctx.update(&message[split..]);
            assert_eq!(
                ctx.finalize(),
                sha512_256(&message),
                "split at {split}"
            );
        }

        // Byte at a time over the longest vector, which crosses the block
        // boundary twice and finishes on a partly filled block.
        let mut ctx = Sha512Trunc256Context::new();
        for byte in TEST_STR6 {
            ctx.update(&[*byte]);
        }
        assert_eq!(ctx.finish(), PRECOMP_HASH6);

        // Nothing fed at all is the empty-input vector, which is the case a
        // context that primed itself lazily would get wrong.
        assert_eq!(Sha512Trunc256Context::new().finalize(), PRECOMP_HASH4);
    }

    /// A cloned context continues independently of its origin.
    ///
    /// `Clone` is derived, so this asserts the property the derive is there
    /// for: a caller digesting several messages that share a prefix primes one
    /// context and clones it, rather than re-feeding the prefix.
    #[test]
    fn a_cloned_context_diverges_from_its_origin() {
        let mut prefix = Sha512Trunc256Context::new();
        prefix.update(b"shared-prefix:");

        let mut first = prefix.clone();
        first.update(b"one");
        let mut second = prefix;
        second.update(b"two");

        assert_eq!(first.finalize(), sha512_256(b"shared-prefix:one"));
        assert_eq!(second.finalize(), sha512_256(b"shared-prefix:two"));
    }

    /// Thirty-two bytes render as sixty-four lowercase characters.
    ///
    /// `lib/vauth/digest.c:145` sizes the destination of
    /// `auth_digest_sha256_to_ascii` at 65 and writes `"%02x"` per byte,
    /// counting a terminator a Rust string does not carry -- hence the `- 1`.
    /// The same renderer serves this digest and the sibling because both are 32
    /// bytes, and `lib/escape.c:218-227` is the uppercase neighbour that must
    /// not be the one reproduced, so every character is checked rather than
    /// sampled.
    #[test]
    fn the_wire_rendering_is_sixty_four_lowercase_hex_characters() {
        let rendered = hex_lower(&sha512_256(TEST_STR1));
        assert_eq!(rendered.len(), 64);
        assert_eq!(rendered.len(), DIGEST_LEN * 2);
        assert_eq!(rendered.len(), SHA256_HEX_BUF_LEN - 1);
        assert!(!rendered.chars().any(|c| c.is_ascii_uppercase()));
        assert!(rendered.chars().all(|c| c.is_ascii_hexdigit()));
        assert_eq!(
            rendered,
            "18d27566bd1ac66b2332d8c54ad43f7bb22079c906d05f491f3f07a28d5c6990"
        );

        // Every one of the eight vectors renders to the same width, which is
        // what lets one 65-byte C buffer serve all of them.
        for digest in [
            PRECOMP_HASH1,
            PRECOMP_HASH2,
            PRECOMP_HASH3,
            PRECOMP_HASH4,
            PRECOMP_HASH5,
            PRECOMP_HASH6,
            PRECOMP_HASH7,
            PRECOMP_HASH8,
        ] {
            let hex = hex_lower(&digest);
            assert_eq!(hex.len(), SHA256_HEX_BUF_LEN - 1);
            assert!(!hex.chars().any(|c| c.is_ascii_uppercase()));
        }
    }

    /// The coherence assertion the marker type exists for.
    ///
    /// Two things are proved at once. `Hmac<D>` bounds `D` on the `digest 0.10`
    /// core traits, so this test would not compile if `sha2` and `hmac` ever
    /// resolved to different `digest` generations -- the build break
    /// `sha2 0.11.0` would cause. And keying through the alias this module
    /// publishes must produce exactly what `crate::crypto::hmac_sha512_256`
    /// produces, which names its hash independently; if the two ever drifted,
    /// the tags would differ.
    #[test]
    fn the_marker_type_keys_the_same_hash_as_the_keyed_module() {
        let key = b"Jefe";
        let message = b"what do ya want for nothing?";

        let mut mac = Hmac::<Sha512Trunc256>::new_from_slice(key)
            .expect("the keyed construction accepts a key of any length");
        mac.update(message);
        let tag: [u8; DIGEST_LEN] = mac.finalize().into_bytes().into();

        assert_eq!(tag.len(), DIGEST_LEN);
        assert_eq!(tag, crate::crypto::hmac_sha512_256(key, message));

        // A key longer than the block is replaced by its own digest
        // (lib/hmac.c:65-74), so the 128 rather than 64 is observable in the
        // tag: a key of exactly 128 bytes is used as given, and one byte more
        // is not.
        let at_the_block = vec![0xaau8; BLOCK_LEN];
        let past_the_block = vec![0xaau8; BLOCK_LEN + 1];
        assert_ne!(
            crate::crypto::hmac_sha512_256(&at_the_block, message),
            crate::crypto::hmac_sha512_256(&past_the_block, message)
        );
    }

    /// The alias must be reachable under the path a sibling module spells, not
    /// only under the `super::` path this test module happens to use.
    ///
    /// `crypto/hmac.rs:52` reaches it as `super::sha512_256::Sha512Trunc256`,
    /// which resolves to the fully qualified path below. Naming it the same way
    /// here makes the visibility a compile-time obligation of this file rather
    /// than something a reader has to take on trust: drop the `pub(crate)` from
    /// the alias and this stops compiling.
    #[test]
    fn the_marker_type_is_reachable_by_fully_qualified_path() {
        const _: Option<crate::crypto::sha512_256::Sha512Trunc256> = None;
        let mut mac =
            Hmac::<crate::crypto::sha512_256::Sha512Trunc256>::new_from_slice(
                b"any key at all",
            )
            .expect("the keyed construction accepts a key of any length");
        mac.update(b"any message");
        assert_eq!(mac.finalize().into_bytes().len(), DIGEST_LEN);
    }

    /// The capability predicate answers, and answers unconditionally.
    ///
    /// `crate::version` pins this signature with a `const _: fn() -> bool`
    /// beside its engine registry, so the only thing left to check is the
    /// value. It is `true` at every feature setting because no feature gates
    /// this module: `lib/curl_sha512_256.h:28`'s two C switches have no Cargo
    /// counterpart, and a `cfg` naming one would compile the digest away in
    /// silence.
    #[test]
    fn the_capability_predicate_reports_the_digest_as_present() {
        assert!(available());

        // And the thing it claims to be present really answers, which is what
        // keeps the claim substantive rather than a bare boolean.
        assert_eq!(sha512_256(TEST_STR3), PRECOMP_HASH3);
    }
}
